const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Plugins.Dictionary,
		C3.Plugins.Json,
		C3.Plugins.Touch,
		C3.Plugins.Date,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Plugins.NinePatch,
		C3.Behaviors.EightDir,
		C3.Behaviors.Physics,
		C3.Behaviors.skymenTrail,
		C3.Behaviors.Rotate,
		C3.Plugins.yagames_sdk,
		C3.Behaviors.skymen_RadialProgress,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Audio.Exps.MasterVolume,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Acts.Destroy,
		C3.Behaviors.skymenTrail.Acts.SetWidthStart,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.skymenTrail.Acts.Reset,
		C3.Behaviors.skymenTrail.Acts.Attach,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Behaviors.Physics.Acts.SetSteppingMode,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Behaviors.Physics.Acts.CreateLimitedRevoluteJoint,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Acts.Scroll,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Behaviors.Timer.Acts.PauseResumeTimer,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.NinePatch.Acts.SetAngle,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.NinePatch.Cnds.IsVisible,
		C3.Plugins.NinePatch.Exps.Angle,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.Physics.Cnds.IsImmovable,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Json.Acts.Destroy,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Particles.Acts.MoveToBottom,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Behaviors.Sin.Acts.UpdateInitialState,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Particles.Cnds.IsOnLayer,
		C3.Plugins.Particles.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.JavaScriptInEvents.Generalsheet_Event309_Act1,
		C3.Plugins.yagames_sdk.Acts.Purchase,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Exps.AnimationFrameTag,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Cnds.IsOnLayer,
		C3.Plugins.Text.Cnds.PickDistance,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemRemoved,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Arr.Acts.Destroy,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Arr.Acts.Sort,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Json.Acts.SetArray,
		C3.Plugins.Json.Acts.SetObject,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Plugins.NinePatch.Acts.MoveToTop,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.NinePatch.Acts.AddChild,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.HasParent,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetEffect,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.System.Acts.SetLayerEffectParam,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.NinePatch.Cnds.CompareX,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.TiledBg.Cnds.CompareOpacity,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.TiledBg.Acts.MoveToLayer,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Behaviors.Timer.Acts.PauseResumeAllTimers,
		C3.Behaviors.Tween.Exps.PlaybackRate,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.Date.Exps.Difference,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Date.Exps.ToTimerMinutes,
		C3.Plugins.Date.Exps.ToTimerSeconds,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.System.Cnds.PickNth,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Particles.Acts.MoveToTop,
		C3.Behaviors.skymen_RadialProgress.Acts.SetValue,
		C3.Plugins.Sprite.Acts.RotateTowardAngle,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Behaviors.skymen_RadialProgress.Exps.Value,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.yagames_sdk.Acts.LoadingAPIReady,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.JavaScriptInEvents.Loadingsheet_Event7_Act1,
		C3.JavaScriptInEvents.Loadingsheet_Event7_Act3,
		C3.JavaScriptInEvents.Adsheet_Event1_Act1,
		C3.JavaScriptInEvents.Adsheet_Event2_Act1,
		C3.Plugins.Audio.Acts.SetMasterVolume
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{Mouse: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{ArrayCountries: 0},
	{Browser: 0},
	{DictionaryColors: 0},
	{DictionarySkin: 0},
	{JSONMatches: 0},
	{Touch: 0},
	{JSON_Balls: 0},
	{Date: 0},
	{JSON_Gatalog: 0},
	{JSFX: 0},
	{JMUSIC: 0},
	{JCOINS: 0},
	{W: 0},
	{H: 0},
	{Active: 0},
	{BtnContinue: 0},
	{BtnInfo: 0},
	{BtnNewGame: 0},
	{BtnSFX: 0},
	{BtnBack: 0},
	{BtnClose: 0},
	{BtnDoonDook: 0},
	{BtnNext: 0},
	{BtnNo: 0},
	{BtnPlay: 0},
	{BtnRandomSelect: 0},
	{BtnYes: 0},
	{BtnHome: 0},
	{BtnNextMatch: 0},
	{BtnPause: 0},
	{BtnResume: 0},
	{Sine: 0},
	{BtnWatchAds: 0},
	{BtnWatchAdsRandom: 0},
	{BtnRandom: 0},
	{BtnStore: 0},
	{BtnAdFreeCoins: 0},
	{BtnAdX2Coins: 0},
	{BtnBuyCoin: 0},
	{num: 0},
	{parrentUID: 0},
	{widthStart: 0},
	{MainPlayer: 0},
	{Colored: 0},
	{ArmLeft: 0},
	{ArmRight: 0},
	{Body: 0},
	{Head: 0},
	{LegLeft: 0},
	{LegRight: 0},
	{type: 0},
	{AdType: 0},
	{PackName: 0},
	{Tween: 0},
	{txt: 0},
	{Type: 0},
	{txtAlert: 0},
	{txtCPUGoals: 0},
	{txtPopupTitle: 0},
	{txtResult: 0},
	{txtResultPopup: 0},
	{MType: 0},
	{txtSelectedCountry: 0},
	{txtSelectedCountry2: 0},
	{txtTap: 0},
	{Timer: 0},
	{txtTimer: 0},
	{txtUserGoals: 0},
	{txtVersion: 0},
	{txtWarning: 0},
	{txtCoinsPrice: 0},
	{txtPUpCurrentTime: 0},
	{BallNum: 0},
	{StoreBalls: 0},
	{ParticleGetCoin: 0},
	{state: 0},
	{CoinIcon: 0},
	{Title: 0},
	{Popup: 0},
	{Black: 0},
	{WarningIcon: 0},
	{JacpotIndex: 0},
	{MyY: 0},
	{Team2: 0},
	{GameIndex: 0},
	{Selected: 0},
	{Flag: 0},
	{FlagsParent: 0},
	{Selector: 0},
	{WayBg: 0},
	{Num: 0},
	{StartX: 0},
	{StartY: 0},
	{StartW: 0},
	{StartH: 0},
	{PlaceHolder: 0},
	{WayBgCover: 0},
	{PlaceHolderBorder: 0},
	{Cover: 0},
	{Fade: 0},
	{Go: 0},
	{"8Direction": 0},
	{JackpotController: 0},
	{WhiteShock: 0},
	{GoalTop: 0},
	{In: 0},
	{GoalChecker: 0},
	{Sleeve: 0},
	{Short: 0},
	{name: 0},
	{Colors: 0},
	{Goalpost: 0},
	{Physics: 0},
	{Solid2: 0},
	{Goal: 0},
	{SolidChecker1: 0},
	{SolidChecker2: 0},
	{TrailRenderer: 0},
	{Trail: 0},
	{CoverBlack: 0},
	{Dir: 0},
	{MsgGoal: 0},
	{WorldCup: 0},
	{Star: 0},
	{ParticlesStars: 0},
	{Rotate: 0},
	{Sine2: 0},
	{Confetti: 0},
	{Particles: 0},
	{Particles2: 0},
	{Shining: 0},
	{TitleShining: 0},
	{Pattern: 0},
	{Tick: 0},
	{Hair: 0},
	{Face: 0},
	{Field: 0},
	{Glass: 0},
	{AdPanel: 0},
	{ResultBoard: 0},
	{InGameCup: 0},
	{DarkSide: 0},
	{TiledBackground2: 0},
	{StadiumBack: 0},
	{Light: 0},
	{WorldCup2: 0},
	{Hand: 0},
	{DeviceIcon: 0},
	{Arrow: 0},
	{firstContact: 0},
	{ball: 0},
	{GameController: 0},
	{Ground: 0},
	{Solid: 0},
	{touchStart: 0},
	{txt2: 0},
	{IsProgress: 0},
	{AdsOfferProgressFrame: 0},
	{MaskOfferProgress2: 0},
	{MaskOfferProgress3: 0},
	{AdsOfferProgress: 0},
	{AdsOfferProgressFrame2: 0},
	{roadToFinalBg: 0},
	{SelectedBox: 0},
	{Coins: 0},
	{YandexGamesSDK: 0},
	{ParticlesStars2: 0},
	{SuccessUnlockedBall: 0},
	{Value: 0},
	{GetCoinIcon: 0},
	{MyId: 0},
	{CoinPacks: 0},
	{TutPowerUpBalloon: 0},
	{txtPAmount: 0},
	{BtnPowerUp: 0},
	{txtPUpgradeButton: 0},
	{BtnGetUpgradePower: 0},
	{txtPowerTut: 0},
	{txtPowerupLevel: 0},
	{BtnUpgradePowerup: 0},
	{txtPUpgradePrice: 0},
	{txtPowerupTime: 0},
	{txtPUpgradeTitle: 0},
	{TimeIcon: 0},
	{txtCoinError: 0},
	{txtPFullUpgrade: 0},
	{ParticlesStars3: 0},
	{ParticleSpwanPos: 0},
	{txtFreePowerupTitle: 0},
	{BtnPowerUpAd: 0},
	{BtnBuyPowerUp: 0},
	{txtPWatchAd: 0},
	{txtFreePowerupCount: 0},
	{PowerUpIcon: 0},
	{txtPoweUpPrice: 0},
	{RadialProgress: 0},
	{PowerUpProgress: 0},
	{ice: 0},
	{PowerUpProgress2: 0},
	{CirclePAmount: 0},
	{IAPLoadingSpinner: 0},
	{CurrencyIcon: 0},
	{Pin: 0},
	{FBody: 0},
	{FButtons: 0},
	{FFlag: 0},
	{FGoal: 0},
	{FSolid: 0},
	{FLang: 0},
	{fText: 0},
	{FLang2: 0},
	{GameplayState: 0},
	{gravity: 0},
	{Countries: 0},
	{UserGoals: 0},
	{CPUGoals: 0},
	{RandomDistance: 0},
	{TouchAvailable: 0},
	{WaitForGoldenGoal: 0},
	{SecondValue: 0},
	{Cup: 0},
	{CPU_OnSolid: 0},
	{CPU_OnGroundd: 0},
	{CPUGetBack: 0},
	{Touched: 0},
	{EndTime: 0},
	{AdsOffered: 0},
	{vType: 0},
	{ID: 0},
	{vSpc: 0},
	{Magnitude: 0},
	{vTime: 0},
	{vNum: 0},
	{vScale: 0},
	{ByCPU: 0},
	{vRnd: 0},
	{vDist: 0},
	{vRndHitOpponent: 0},
	{GoalDifference: 0},
	{vResult: 0},
	{vCountry: 0},
	{KitNum: 0},
	{vCountry2: 0},
	{Wait: 0},
	{vX: 0},
	{vY: 0},
	{x: 0},
	{y: 0},
	{vWinner: 0},
	{Amount: 0},
	{PackID: 0},
	{State: 0},
	{Music: 0},
	{SFX: 0},
	{ScreenWidth: 0},
	{ScreenHeight: 0},
	{FlagSize: 0},
	{Spc: 0},
	{RateA: 0},
	{RateB: 0},
	{RateC: 0},
	{RateA_Main: 0},
	{RateB_Main: 0},
	{RateC_Main: 0},
	{SelectedCountry: 0},
	{NextMatch: 0},
	{GameNum: 0},
	{Lang: 0},
	{LangIsLoaded: 0},
	{vLeft: 0},
	{vRight: 0},
	{vTop: 0},
	{vBottom: 0},
	{GridW: 0},
	{GridWIndex: 0},
	{vS: 0},
	{Size: 0},
	{LastTimeScale: 0},
	{IsTimeScaleSet: 0},
	{FreeCoinsReward: 0},
	{packname: 0},
	{FlagID: 0},
	{PopupName: 0},
	{Do: 0},
	{SoundName: 0},
	{RandomPrice: 0},
	{GiftTime: 0},
	{GiftTime_SecStart: 0},
	{GiftTime_MinStart: 0},
	{GiftTime_HourStart: 0},
	{GiftTimeDifference: 0},
	{FreeCoinsTime: 0},
	{FreeCoins_SecStart: 0},
	{FreeCoins_MinStart: 0},
	{FreeCoins_HourStart: 0},
	{FreeCoinsDifference: 0},
	{vTimeStamp: 0},
	{vTimeStamp2: 0},
	{Coins2: 0},
	{Count: 0},
	{XPos: 0},
	{YPos: 0},
	{CoinDist: 0},
	{CoinAngle: 0},
	{SelectedNum: 0},
	{do: 0},
	{PowerUp: 0},
	{PowerUpLevel: 0},
	{PowerUpUpgradePrice: 0},
	{PowerUpPrice: 0},
	{PowerUpTime: 0},
	{CurrentTime: 0},
	{InPowerUp: 0},
	{AdWatched: 0},
	{LastX: 0},
	{LastY: 0},
	{LastAngle: 0},
	{PowerUpTut: 0},
	{PowerState: 0},
	{RewardedState: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	ArrayCountries: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	DictionaryColors: class extends self.IDictionaryInstance {},
	DictionarySkin: class extends self.IDictionaryInstance {},
	JSONMatches: class extends self.IJSONInstance {},
	Touch: class extends self.IInstance {},
	JSON_Balls: class extends self.IJSONInstance {},
	Date: class extends self.IInstance {},
	JSON_Gatalog: class extends self.IJSONInstance {},
	JSFX: class extends self.IJSONInstance {},
	JMUSIC: class extends self.IJSONInstance {},
	JCOINS: class extends self.IJSONInstance {},
	BtnContinue: class extends self.ISpriteInstance {},
	BtnInfo: class extends self.ISpriteInstance {},
	BtnNewGame: class extends self.ISpriteInstance {},
	BtnSFX: class extends self.ISpriteInstance {},
	BtnBack: class extends self.ISpriteInstance {},
	BtnClose: class extends self.ISpriteInstance {},
	BtnDoonDook: class extends self.ISpriteInstance {},
	BtnNext: class extends self.ISpriteInstance {},
	BtnNo: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	BtnRandomSelect: class extends self.ISpriteInstance {},
	BtnYes: class extends self.ISpriteInstance {},
	BtnHome: class extends self.ISpriteInstance {},
	BtnNextMatch: class extends self.ISpriteInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	BtnResume: class extends self.ISpriteInstance {},
	BtnWatchAds: class extends self.ISpriteInstance {},
	BtnWatchAdsRandom: class extends self.ISpriteInstance {},
	BtnRandom: class extends self.ISpriteInstance {},
	BtnStore: class extends self.ISpriteInstance {},
	BtnAdFreeCoins: class extends self.ISpriteInstance {},
	BtnAdX2Coins: class extends self.ISpriteInstance {},
	BtnBuyCoin: class extends self.ISpriteInstance {},
	ArmLeft: class extends self.ISpriteInstance {},
	ArmRight: class extends self.ISpriteInstance {},
	Body: class extends self.ISpriteInstance {},
	Head: class extends self.ISpriteInstance {},
	LegLeft: class extends self.ISpriteInstance {},
	LegRight: class extends self.ISpriteInstance {},
	txt: class extends self.ITextInstance {},
	txtAlert: class extends self.ITextInstance {},
	txtCPUGoals: class extends self.ITextInstance {},
	txtPopupTitle: class extends self.ITextInstance {},
	txtResult: class extends self.ITextInstance {},
	txtResultPopup: class extends self.ITextInstance {},
	txtSelectedCountry: class extends self.ITextInstance {},
	txtSelectedCountry2: class extends self.ITextInstance {},
	txtTap: class extends self.ITextInstance {},
	txtTimer: class extends self.ITextInstance {},
	txtUserGoals: class extends self.ITextInstance {},
	txtVersion: class extends self.ITextInstance {},
	txtWarning: class extends self.ITextInstance {},
	txtCoinsPrice: class extends self.ITextInstance {},
	txtPUpCurrentTime: class extends self.ITextInstance {},
	StoreBalls: class extends self.ISpriteInstance {},
	ParticleGetCoin: class extends self.IParticlesInstance {},
	CoinIcon: class extends self.ISpriteInstance {},
	Title: class extends self.ISpriteInstance {},
	Popup: class extends self.ISpriteInstance {},
	Black: class extends self.ITiledBackgroundInstance {},
	WarningIcon: class extends self.ISpriteInstance {},
	Flag: class extends self.ISpriteInstance {},
	FlagsParent: class extends self.ISpriteInstance {},
	Selector: class extends self.ISpriteInstance {},
	WayBg: class extends self.IWorldInstance {},
	PlaceHolder: class extends self.IWorldInstance {},
	WayBgCover: class extends self.IWorldInstance {},
	PlaceHolderBorder: class extends self.IWorldInstance {},
	Cover: class extends self.ITiledBackgroundInstance {},
	Fade: class extends self.ISpriteInstance {},
	JackpotController: class extends self.ISpriteInstance {},
	WhiteShock: class extends self.ISpriteInstance {},
	GoalTop: class extends self.ISpriteInstance {},
	GoalChecker: class extends self.ISpriteInstance {},
	Sleeve: class extends self.ISpriteInstance {},
	Short: class extends self.ISpriteInstance {},
	Colors: class extends self.ISpriteInstance {},
	Solid2: class extends self.ISpriteInstance {},
	Goal: class extends self.ISpriteInstance {},
	SolidChecker1: class extends self.ISpriteInstance {},
	SolidChecker2: class extends self.ISpriteInstance {},
	Trail: class extends self.ISpriteInstance {},
	CoverBlack: class extends self.ITiledBackgroundInstance {},
	MsgGoal: class extends self.ISpriteInstance {},
	WorldCup: class extends self.ISpriteInstance {},
	Star: class extends self.ISpriteInstance {},
	ParticlesStars: class extends self.IParticlesInstance {},
	Confetti: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Shining: class extends self.ISpriteInstance {},
	TitleShining: class extends self.ISpriteInstance {},
	Pattern: class extends self.ITiledBackgroundInstance {},
	Tick: class extends self.ISpriteInstance {},
	Hair: class extends self.ISpriteInstance {},
	Face: class extends self.ISpriteInstance {},
	Field: class extends self.ISpriteInstance {},
	Glass: class extends self.ITiledBackgroundInstance {},
	AdPanel: class extends self.ITiledBackgroundInstance {},
	ResultBoard: class extends self.ISpriteInstance {},
	InGameCup: class extends self.ISpriteInstance {},
	DarkSide: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	StadiumBack: class extends self.ISpriteInstance {},
	Light: class extends self.ISpriteInstance {},
	WorldCup2: class extends self.ISpriteInstance {},
	Hand: class extends self.ISpriteInstance {},
	DeviceIcon: class extends self.ISpriteInstance {},
	Arrow: class extends self.IWorldInstance {},
	ball: class extends self.ISpriteInstance {},
	GameController: class extends self.ISpriteInstance {},
	Solid: class extends self.ISpriteInstance {},
	touchStart: class extends self.ISpriteInstance {},
	txt2: class extends self.ITextInstance {},
	AdsOfferProgressFrame: class extends self.ISpriteInstance {},
	MaskOfferProgress2: class extends self.ISpriteInstance {},
	MaskOfferProgress3: class extends self.ISpriteInstance {},
	AdsOfferProgress: class extends self.ITiledBackgroundInstance {},
	AdsOfferProgressFrame2: class extends self.ISpriteInstance {},
	roadToFinalBg: class extends self.ISpriteInstance {},
	SelectedBox: class extends self.ISpriteInstance {},
	Coins: class extends self.ISpriteInstance {},
	YandexGamesSDK: class extends self.IInstance {},
	ParticlesStars2: class extends self.IParticlesInstance {},
	SuccessUnlockedBall: class extends self.ISpriteInstance {},
	GetCoinIcon: class extends self.ISpriteInstance {},
	CoinPacks: class extends self.ISpriteInstance {},
	TutPowerUpBalloon: class extends self.ISpriteInstance {},
	txtPAmount: class extends self.ITextInstance {},
	BtnPowerUp: class extends self.ISpriteInstance {},
	txtPUpgradeButton: class extends self.ITextInstance {},
	BtnGetUpgradePower: class extends self.ISpriteInstance {},
	txtPowerTut: class extends self.ITextInstance {},
	txtPowerupLevel: class extends self.ITextInstance {},
	BtnUpgradePowerup: class extends self.ISpriteInstance {},
	txtPUpgradePrice: class extends self.ITextInstance {},
	txtPowerupTime: class extends self.ITextInstance {},
	txtPUpgradeTitle: class extends self.ITextInstance {},
	TimeIcon: class extends self.ISpriteInstance {},
	txtCoinError: class extends self.ITextInstance {},
	txtPFullUpgrade: class extends self.ITextInstance {},
	ParticlesStars3: class extends self.IParticlesInstance {},
	ParticleSpwanPos: class extends self.ISpriteInstance {},
	txtFreePowerupTitle: class extends self.ITextInstance {},
	BtnPowerUpAd: class extends self.ISpriteInstance {},
	BtnBuyPowerUp: class extends self.ISpriteInstance {},
	txtPWatchAd: class extends self.ITextInstance {},
	txtFreePowerupCount: class extends self.ITextInstance {},
	PowerUpIcon: class extends self.ISpriteInstance {},
	txtPoweUpPrice: class extends self.ITextInstance {},
	PowerUpProgress: class extends self.ISpriteInstance {},
	ice: class extends self.ISpriteInstance {},
	PowerUpProgress2: class extends self.ISpriteInstance {},
	CirclePAmount: class extends self.ISpriteInstance {},
	IAPLoadingSpinner: class extends self.ISpriteInstance {},
	CurrencyIcon: class extends self.ISpriteInstance {},
	FBody: class extends self.ISpriteInstance {},
	FButtons: class extends self.ISpriteInstance {},
	FFlag: class extends self.ISpriteInstance {},
	FGoal: class extends self.ISpriteInstance {},
	FSolid: class extends self.ISpriteInstance {},
	FLang: class extends self.ISpriteInstance {},
	fText: class extends self.ITextInstance {},
	FLang2: class extends self.ISpriteInstance {}
}